Models/ErrorViewModel.cs
using System;

namespace TennesseeStockings.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Stock.cs
using System;

namespace TennesseeStockings.Models
{    
    public class Stock
    {
        public int Id {get;set;}
        public string Stream {get;set;}
        public DateTime Stocking {get;set;}

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TennesseeStockings.Models;

namespace TennesseeStockings.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/StockingsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TennesseeStockings.Models;
using TennesseeStockings;

public class StockingsController : Controller
{
    private DataContext _context;

    public StockingsController(DataContext context)
    {
        _context = context;
    }

    public async Task<IActionResult> Index(string searchStream)
    {
        ViewData["CurrentFilter"] = searchStream;

        //var stockings = await _context.Stockings.ToListAsync();
        var stockings = from s in _context.Stockings select s;

        if(!String.IsNullOrEmpty(searchStream))
        {
            stockings=stockings.Where(s => s.Stream.Contains(searchStream));            
        }       

        return View(await stockings.AsNoTracking().ToListAsync());
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(Stock stocks)
    {
        // validate that our model meets the requirement
        if (ModelState.IsValid)
        {
            try
            {
                // update the ef core context in memory 
                _context.Add(stocks);

                // sync the changes of ef code in memory with the database
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ModelState.AddModelError(string.Empty, $"Something went wrong {ex.Message}");
            }
        }

        ModelState.AddModelError(string.Empty, $"Something went wrong, invalid model");

        // We return the object back to view
        return View(stocks);
    }

    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        var exist = await _context.Stockings.Where(x => x.Id == id).FirstOrDefaultAsync();

        return View(exist);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(Stock stocks)
    {
        // validate that our model meets the requirement
        if (ModelState.IsValid)
        {
            try
            {
                // Check if the stocking exist based on the id
                var exist = _context.Stockings.Where(x => x.Id == stocks.Id).FirstOrDefault();

                // if the stocking is not null we update the information
                if(exist != null)
                {
                    exist.Stream = stocks.Stream;
                    exist.Stocking = stocks.Stocking;
                    
                    // we save the changes into the db
                    await _context.SaveChangesAsync();

                    return RedirectToAction("Index");
                }
            }
            catch(Exception ex)
            {
                ModelState.AddModelError(string.Empty, $"Something went wrong {ex.Message}");
            }
        }

        ModelState.AddModelError(string.Empty, $"Something went wrong, invalid model");

        return View(stocks);
    }

    [HttpGet]
    public async Task<IActionResult> Delete(int id)
    {
        var exist = await _context.Stockings.Where(x => x.Id == id).FirstOrDefaultAsync();

        return View(exist);
    }

    [HttpPost]
    public async Task<IActionResult> Delete(Stock stocks)
    {
        if (ModelState.IsValid)
        {
            try
            {
                var exist = _context.Stockings.Where(x => x.Id == stocks.Id).FirstOrDefault();

                if(exist != null)
                {
                    _context.Remove(exist);
                    await _context.SaveChangesAsync();

                    return RedirectToAction("Index");
                } 
            }
            catch(Exception ex)
            {
                ModelState.AddModelError(string.Empty, $"Something went wrong {ex.Message}");
            }
        }

        ModelState.AddModelError(string.Empty, $"Something went wrong, invalid model");

        return View();
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TennesseeStockings</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TennesseeStockings</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stockings"
                                asp-action="Index">Stockings</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TennesseeStockings - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Views/Stockings/Create.cshtml
@model TennesseeStockings.Models.Stock

<form asp-action="Create" asp-area="Stockings" method="post">
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <label>Stream:</label>
                <input asp-for="Stream" type="text" class="form-control required" placeholder="Enter Stream"
                    tabindex="1">
            </div>
            <div class="form-group">
                <label>Stocking Date:</label>
                <input asp-for="Stocking" type="text" class="form-control required" placeholder="Enter Stocking Date"
                    tabindex="2">
            </div>
            <div class="form-group">
                <div asp-validation-summary="All" class="text-danger"></div>
            </div>
            <div class="card-footer">
                <center>
                    <button type="submit" class="btn btn-primary">Create Stocking</button>
                    <a asp-action="Index" asp-controller="Stockings" class="btn btn-secondary">Cancel</a>
                </center>
            </div>
        </div>
    </div>
</form>

Views/Stockings/Delete.cshtml
@model TennesseeStockings.Models.Stock

<form asp-action="Delete" asp-area="Stockings" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <label>Stream:</label>
                <input asp-for="Stream" type="text" disabled class="form-control required" placeholder="Enter Stream"
                    tabindex="1">
            </div>
            <div class="form-group">
                <label>Stocking:</label>
                <input asp-for="Stocking" type="text" disabled class="form-control required"
                    placeholder="Enter Stocking" tabindex="2">
            </div>
            <div class="form-group">
                <div asp-validation-summary="All" class="text-danger"></div>
            </div>
            <div class="card-footer">
                <center>
                    <button type="submit" class="btn btn-danger">Delete Stocking</button>
                    <a asp-action="Index" asp-controller="Stockings" class="btn btn-secondary">Cancel</a>
                </center>
            </div>
        </div>
    </div>
</form>

Views/Stockings/Edit.cshtml
@model TennesseeStockings.Models.Stock

<form asp-action="Edit" asp-area="Stockings" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <label>Stream:</label>
                <input asp-for="Stream" type="text" class="form-control required" placeholder="Enter stream"
                    tabindex="1">
            </div>
            <div class="form-group">
                <label>Stocking:</label>
                <input asp-for="Stocking" type="text" class="form-control required" placeholder="Enter stocking"
                    tabindex="2">
            </div>
            <div class="form-group">
                <div asp-validation-summary="All" class="text-danger"></div>
            </div>
            <div class="card-footer">
                <center>
                    <button type="submit" class="btn btn-warning">Update Stocking</button>
                    <a asp-action="Index" asp-controller="Stockings" class="btn btn-secondary">Cancel</a>
                </center>
            </div>
        </div>
    </div>
</form>

Views/Stockings/Index.cshtml
@model List<TennesseeStockings.Models.Stock>

<form asp-action="Index" method="get">
    <div>
        <p>
            Search Stream: <input type="text" name="searchStream" value="" />
            <input type="submit" value="Search" class="btn btn-info" />
            <a asp-action="Index">Remove Filter</a>
        </p>
    </div>
</form>

<div class="row">
    <div class="col-md-12">
        <a asp-action="Create" asp-controller="Stockings" class="btn btn-info">Create</a>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table">
            <thead>
                <tr>
                    <td>Stream</td>
                    <td>Stocking</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Stream</td>
                        <td>@item.Stocking.ToShortDateString()</td>
                        <td>
                            <a asp-action="Edit" asp-controller="Stockings" asp-route-id="@item.Id">
                                Edit
                            </a>
                            <a asp-action="Delete" asp-controller="Stockings" asp-route-id="@item.Id">
                                Delete
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>